### ISSUE TITLE
Pourquoi la classe Str est elle dans le fichier StrTest ??

### ISSUE THREAD

**Issue by mathieutu** [OliveCh12/Workshop-POO-String-#1]
https://github.com/OliveCh12/Workshop-POO-String-/blob/99ea1cb93464f31894627886bc81bac63db6995d/src/StrTest.php#L4

**Comment by OliveCh12** [comment]
J'ai inversé les fichiers "**Str.php**" et "**StrTest.php**". Faute de logique de ma part.
